# Generated by Django 2.1.2 on 2018-11-20 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='nombre del control', max_length=100)),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('enUso', models.BooleanField(default=True, help_text='si el control es el que actualmente se usa en las corridas')),
            ],
        ),
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('valor', models.FloatField(help_text='El valor del control en la corrida')),
                ('valido', models.BooleanField(default=True, help_text='si el valor puede ser tomado para calcular media y sd acumulado')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verControl.Control')),
            ],
        ),
        migrations.CreateModel(
            name='Determinacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='nombre de la determinación', max_length=100)),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo', models.CharField(blank=True, help_text='identificación dada por el fabricante', max_length=100, null=True)),
                ('unidades', models.CharField(help_text='unidades con que se informa la determinación', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='nombre del Equipo -- Cómo lo identifica el laboratorio', max_length=100)),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, help_text='Se puede dar el nombre del equipo, modelo, u otra particularidad del mismo', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='codigo que identifica el lote, dado por el fabricante.', max_length=100)),
                ('fechaVenc', models.DateField(verbose_name='Fecha Vencimiento')),
            ],
        ),
        migrations.CreateModel(
            name='ValAcu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FloatField()),
                ('sd', models.FloatField()),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verControl.Control')),
                ('deter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verControl.Determinacion')),
            ],
        ),
        migrations.CreateModel(
            name='ValFabr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FloatField(help_text='El valor de la media que informa el fabricante')),
                ('sd', models.FloatField()),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verControl.Control')),
                ('deter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verControl.Determinacion')),
            ],
        ),
        migrations.AddField(
            model_name='determinacion',
            name='equipo',
            field=models.ForeignKey(help_text='Equipo en que se procesa la determinación, si se procesa en diversos equipos cada equipo tiene su determinación.', on_delete=django.db.models.deletion.CASCADE, to='verControl.Equipo'),
        ),
        migrations.AddField(
            model_name='corrida',
            name='determinacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verControl.Determinacion'),
        ),
        migrations.AddField(
            model_name='control',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verControl.Lote'),
        ),
    ]
